// This stylesheet import is generated by @jvlk/rescript-css.
import "./App.css";
// Generated by ReScript, PLEASE EDIT WITH CARE


let className = "rc_1d5myqo_0";

let html = `<main class="${className}"><h1>ReScript 13 preview</h1><p>CSS compiled with ReScript 13.0.0-alpha.6 and Vite 8.</p></main>`;

export {
  className,
  html,
}
/* className Not a pure module */
