// This stylesheet import is generated by @jvlk/rescript-css.
import "./App.css";
globalThis[Symbol.for("@jvlk/rescript-css.collector")] = { scope: "/home/josh/Dev/rescript-css/examples/rescript-11/src/App.res.js", styles: [], rules: [], keyframes: [], fontFaces: [], properties: [], scopes: [], pages: [], layerOrder: [], nextRuleOrder: 0, variables: [], rootCssText: "" };
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@jvlk/rescript-css/src/Css.res.js";

var className = Css.$$class(undefined, {
      display: "Grid",
      maxWidth: {
        TAG: "Rem",
        _0: 32.0
      },
      margin: "Auto",
      padding: {
        TAG: "Rem",
        _0: 1.5
      },
      gap: {
        TAG: "Rem",
        _0: 0.75
      },
      color: {
        TAG: "Named",
        _0: "#0f172a"
      },
      background: "#ecfeff",
      borderRadius: {
        TAG: "Raw",
        _0: "8px"
      },
      hover: Css.style(undefined, {
            background: "#cffafe"
          })
    });

var html = "<main class=\"" + className + "\"><h1>ReScript 11</h1><p>CSS compiled with ReScript 11.1.4 and Vite 8.</p></main>";

export {
  className ,
  html ,
}
/* className Not a pure module */
