// This stylesheet import is generated by @jvlk/rescript-css.
import "./Animations.css";
// Generated by ReScript, PLEASE EDIT WITH CARE


let fadeIn = "rc_kf_n2l8dy";

export {
  fadeIn,
}
/* fadeIn Not a pure module */
