// This stylesheet import is generated by @jvlk/rescript-css.
import "./Button.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.js";
import * as CssValue from "@jvlk/rescript-css/src/CssValue.res.js";
import "./Animations.res.js";

let radius = CssValue.BorderRadius.single({
  TAG: "Px",
  _0: 6
});

let tmp;

tmp = radius.TAG === "Ok" ? radius._0 : ({
    TAG: "Raw",
    _0: "6px"
  });

let duration = CssValue.Duration.ms(180.0);

let tmp$1;

tmp$1 = duration.TAG === "Ok" ? duration._0 : CssValue.Duration.zero;

let className = "rc_2m213x_0";

let html = `<button class="` + className + `">Shared variables</button>`;

export {
  className,
  html,
}
/* className Not a pure module */
