// This stylesheet import is generated by @jvlk/rescript-css.
import "./Button.css";
// Generated by ReScript, PLEASE EDIT WITH CARE


let className = "rc_2m213x_0";

let html = `<button class="` + className + `">Typed CSS</button>`;

export {
  className,
  html,
}
/* className Not a pure module */
