// This stylesheet import is generated by @jvlk/rescript-css.
import "./Card.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.js";

let className = "rc_1x0uhsv_0";

let html = `<article class="` + className + `">Scoped variable overrides</article>`;

export {
  className,
  html,
}
/* className Not a pure module */
