// This stylesheet import is generated by @jvlk/rescript-css.
import "./Card.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.js";
import * as CssValue from "@jvlk/rescript-css/src/CssValue.res.js";

let radius = CssValue.BorderRadius.single({
  TAG: "Px",
  _0: 8
});

let tmp;

tmp = radius.TAG === "Ok" ? radius._0 : ({
    TAG: "Raw",
    _0: "8px"
  });

let className = "rc_1x0uhsv_0";

let html = `<article class="` + className + `"><h1>Scoped variable overrides</h1></article>`;

export {
  className,
  html,
}
/* className Not a pure module */
