// This stylesheet import is generated by @jvlk/rescript-css.
import "./Component.css";
// Generated by ReScript, PLEASE EDIT WITH CARE


let button = "rc_8q9284_0";

export {
  button,
}
/* button Not a pure module */
