// This stylesheet import is generated by @jvlk/rescript-css.
import "./Fonts.css";
// Generated by ReScript, PLEASE EDIT WITH CARE


let inter = "\"Inter\"";

export {
  inter,
}
/* inter Not a pure module */
