// This stylesheet import is generated by @jvlk/rescript-css.
import "./GlobalStyles.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.js";
import "./Fonts.res.js";




/*  Not a pure module */
