let borderValue = (value, fallback) =>
  switch CssValue.BorderWidthValue.length(value) {
  | Ok(value) => value
  | Error(_) => CssValue.BorderWidthValue.Raw(fallback)
  }

let border1 = borderValue(Px(1), "1px")
let border2 = borderValue(Px(2), "2px")
let border3 = borderValue(Px(3), "3px")
let borderQuarterRem = borderValue(Rem(0.25), "0.25rem")

let circularRadius = (value, fallback) =>
  switch CssValue.CornerRadius.circular(value) {
  | Ok(value) => value
  | Error(_) => CssValue.CornerRadius.Raw(fallback)
  }

let ellipticalRadius = (horizontal, vertical, fallback) =>
  switch CssValue.CornerRadius.elliptical(~horizontal, ~vertical) {
  | Ok(value) => value
  | Error(_) => CssValue.CornerRadius.Raw(fallback)
  }

// This fixture is compiled by the basic example and keeps every modern-property field type-checked.
let showcase = Css.style({
  anchorName: "--trigger",
  anchorScope: "--trigger",
  positionAnchor: "--trigger",
  positionArea: "top span-all",
  positionTry: "most-width flip-block",
  positionTryFallbacks: "--below, flip-block",
  positionTryOrder: MostInlineSize,
  positionVisibility: Conditions([AnchorVisible, NoOverflow]),
  containIntrinsicSize: "auto 300px",
  containIntrinsicWidth: AutoLength(Rem(20.0)),
  containIntrinsicHeight: None,
  containIntrinsicBlockSize: AutoLength(Rem(24.0)),
  containIntrinsicInlineSize: Length(Rem(18.0)),
  colorScheme: "light dark",
  forcedColorAdjust: PreserveParentColor,
  printColorAdjust: Exact,
  fontVariationSettings: "\"wght\" 650",
  fontPalette: "--brand-palette",
  fontSynthesis: Values([Weight, Style]),
  fontSizeAdjust: Metric(CapHeight, 0.7),
  textWrap: Balance,
  textWrapMode: NoWrap,
  textWrapStyle: Pretty,
  textEmphasis: "filled sesame red",
  textOrientation: Upright,
  unicodeBidi: Isolate,
  hangingPunctuation: Values([First, AllowEnd]),
  lineClamp: Lines(3),
  borderBlockStart: "1px solid red",
  borderBlockEnd: "2px dashed blue",
  borderInlineStart: "1px dotted green",
  borderInlineEnd: "3px double black",
  borderBlockColor: Named("red"),
  borderBlockStartColor: Named("red"),
  borderBlockEndColor: Named("blue"),
  borderInlineColor: Named("blue"),
  borderInlineStartColor: Named("green"),
  borderInlineEndColor: Named("black"),
  borderBlockStyle: Solid,
  borderBlockStartStyle: Solid,
  borderBlockEndStyle: Dashed,
  borderInlineStyle: Dashed,
  borderInlineStartStyle: Dotted,
  borderInlineEndStyle: Double,
  borderBlockWidth: One(border2),
  borderBlockStartWidth: border1,
  borderBlockEndWidth: border2,
  borderInlineWidth: One(borderQuarterRem),
  borderInlineStartWidth: border1,
  borderInlineEndWidth: border3,
  borderStartStartRadius: circularRadius(Rem(0.5), "0.5rem"),
  borderStartEndRadius: circularRadius(Rem(0.75), "0.75rem"),
  borderEndStartRadius: circularRadius(Px(6), "6px"),
  borderEndEndRadius: ellipticalRadius(Px(8), Px(6), "8px 6px"),
  translate: XY(Rem(1.0), Percent(20.0)),
  rotate: X(Deg(45.0)),
  scale: XY(Number(1.2), Percent(80.0)),
  transformBox: FillBox,
  viewTransitionName: "card-image",
  viewTransitionClass: "card fast-slide",
  transitionBehavior: AllowDiscrete,
  offset: "path(\"M 0 0 L 100 0\") 50%",
  offsetPath: "path(\"M 0 0 L 100 0\")",
  offsetDistance: Percent(50.0),
  offsetPosition: "left top",
  offsetAnchor: "center",
  offsetRotate: AutoAngle(Deg(45.0)),
  fill: Color(Hex("336699")),
  fillOpacity: Number(0.6),
  fillRule: Evenodd,
  stroke: Color(CurrentColor),
  strokeWidth: Px(2),
  strokeOpacity: Percent(75.0),
  strokeLinecap: Round,
  strokeLinejoin: Bevel,
  strokeDasharray: Values([Px(4), Px(2)]),
  strokeDashoffset: Px(1),
  strokeMiterlimit: 4.0,
  paintOrder: Values([Stroke, Fill, Markers]),
  vectorEffect: NonScalingStroke,
  stopColor: Named("gold"),
  stopOpacity: Number(0.8),
  scrollMarginTop: Px(8),
  scrollMarginRight: Px(9),
  scrollMarginBottom: Px(10),
  scrollMarginLeft: Px(11),
  scrollMarginBlock: One(Rem(1.0)),
  scrollMarginBlockStart: Px(12),
  scrollMarginBlockEnd: Px(13),
  scrollMarginInline: Two(Rem(1.25), Px(18)),
  scrollMarginInlineStart: Px(14),
  scrollMarginInlineEnd: Px(15),
  scrollPaddingTop: Px(16),
  scrollPaddingRight: Px(17),
  scrollPaddingBottom: Px(18),
  scrollPaddingLeft: Px(19),
  scrollPaddingBlock: One(Rem(1.5)),
  scrollPaddingBlockStart: Px(20),
  scrollPaddingBlockEnd: Px(21),
  scrollPaddingInline: Two(Rem(1.75), Percent(5.0)),
  scrollPaddingInlineStart: Px(22),
  scrollPaddingInlineEnd: Px(23),
  overscrollBehaviorX: Contain,
  overscrollBehaviorY: None,
  overscrollBehaviorBlock: Contain,
  overscrollBehaviorInline: Auto,
  container: "sidebar / inline-size",
  boxDecorationBreak: Clone,
  breakBefore: AvoidPage,
  breakAfter: Column,
  breakInside: AvoidColumn,
  orphans: 3,
  widows: 3,
  shapeOutside: "circle(50%)",
  shapeMargin: Rem(1.0),
  shapeImageThreshold: Number(0.5),
  fieldSizing: Content,
  interpolateSize: AllowKeywords,
})
