// This stylesheet import is generated by @jvlk/rescript-css.
import "./ModernPropertiesCompile.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssValue from "@jvlk/rescript-css/src/CssValue.res.js";

function borderValue(value, fallback) {
  let value$1 = CssValue.BorderWidthValue.length(value);
  if (value$1.TAG === "Ok") {
    return value$1._0;
  } else {
    return {
      TAG: "Raw",
      _0: fallback
    };
  }
}

let border1 = borderValue({
  TAG: "Px",
  _0: 1
}, "1px");

let border2 = borderValue({
  TAG: "Px",
  _0: 2
}, "2px");

let border3 = borderValue({
  TAG: "Px",
  _0: 3
}, "3px");

let borderQuarterRem = borderValue({
  TAG: "Rem",
  _0: 0.25
}, "0.25rem");

function circularRadius(value, fallback) {
  let value$1 = CssValue.CornerRadius.circular(value);
  if (value$1.TAG === "Ok") {
    return value$1._0;
  } else {
    return {
      TAG: "Raw",
      _0: fallback
    };
  }
}

function ellipticalRadius(horizontal, vertical, fallback) {
  let value = CssValue.CornerRadius.elliptical(horizontal, vertical);
  if (value.TAG === "Ok") {
    return value._0;
  } else {
    return {
      TAG: "Raw",
      _0: fallback
    };
  }
}

let showcase = "rc_cnavlw_0";

export {
  borderValue,
  border1,
  border2,
  border3,
  borderQuarterRem,
  circularRadius,
  ellipticalRadius,
  showcase,
}
/* border1 Not a pure module */
