// This stylesheet import is generated by @jvlk/rescript-css.
import "./StructuredValues.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.js";
import * as CssValue from "@jvlk/rescript-css/src/CssValue.res.js";

let value = CssValue.Duration.ms(180.5);

let duration;

duration = value.TAG === "Ok" ? value._0 : CssValue.Duration.zero;

let value$1 = CssValue.Easing.cubicBezier(0.2, 0.8, 0.2, 1.0);

let easing;

easing = value$1.TAG === "Ok" ? value$1._0 : ({
    TAG: "Raw",
    _0: "ease"
  });

let value$2 = CssValue.Easing.steps(4, "JumpEnd");

let stepped;

stepped = value$2.TAG === "Ok" ? value$2._0 : ({
    TAG: "Raw",
    _0: "steps(4, jump-end)"
  });

let value$3 = CssValue.Time.seconds(-0.25);

let delay;

delay = value$3.TAG === "Ok" ? value$3._0 : CssValue.Time.zero;

let match = CssValue.Easing.linearStop(0.0, undefined);

let match$1 = CssValue.Easing.linearStop(0.75, 60.0);

let match$2 = CssValue.Easing.linearStop(1.0, undefined);

let linearEasing;

if (match.TAG === "Ok" && match$1.TAG === "Ok" && match$2.TAG === "Ok") {
  let value$4 = CssValue.Easing.linearFunction([
    match._0,
    match$1._0,
    match$2._0
  ]);
  linearEasing = value$4.TAG === "Ok" ? value$4._0 : ({
      TAG: "Raw",
      _0: "linear"
    });
} else {
  linearEasing = {
    TAG: "Raw",
    _0: "linear"
  };
}

let match$3 = CssValue.TrackLength.make({
  TAG: "Rem",
  _0: 16.0
});

let match$4 = CssValue.TrackFraction.make(1.0);

let responsiveColumns;

responsiveColumns = match$3.TAG === "Ok" && match$4.TAG === "Ok" ? ({
    TAG: "Tracks",
    _0: [
      {
        TAG: "LineNames",
        _0: ["content-start"]
      },
      {
        TAG: "AutoRepeat",
        _0: "AutoFit",
        _1: [{
            TAG: "FixedBreadth",
            _0: {
              TAG: "Minmax",
              _0: match$3._0,
              _1: {
                TAG: "MaximumFraction",
                _0: match$4._0
              }
            }
          }]
      },
      {
        TAG: "LineNames",
        _0: ["content-end"]
      }
    ]
  }) : ({
    TAG: "Raw",
    _0: "repeat(auto-fit, minmax(16rem, 1fr))"
  });

let value$5 = CssValue.TrackLength.make({
  TAG: "Percent",
  _0: 50.0
});

let autoColumns;

autoColumns = value$5.TAG === "Ok" ? ({
    TAG: "Tracks",
    _0: [{
        TAG: "FitContent",
        _0: value$5._0
      }]
  }) : ({
    TAG: "Raw",
    _0: "fit-content(50%)"
  });

let showcase = "rc_adzrb6_0";

let escapeHatches = "rc_adzrb6_1";

export {
  duration,
  easing,
  stepped,
  delay,
  linearEasing,
  responsiveColumns,
  autoColumns,
  showcase,
  escapeHatches,
}
/* value Not a pure module */
