// This stylesheet import is generated by @jvlk/rescript-css.
import "./Vars.css";
// Generated by ReScript, PLEASE EDIT WITH CARE


let brand = "var(--rc_16lsq83)";

let onBrand = "var(--rc_1se5ehu)";

let surface = "var(--rc_ytpt3h)";

let text = "var(--rc_mszmw5)";

let spaceMd = "var(--rc_w2uaph)";


export {
  brand,
  onBrand,
  surface,
  text,
  spaceMd,
}
/* brand Not a pure module */
