// This stylesheet import is generated by @jvlk/rescript-css.
import "./App.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "./Card.res.js";
import "./Vars.res.js";
import * as Button from "./Button.res.js";
import * as JsxRuntime from "react/jsx-runtime";

let headingText = "Typed CSS variables in ReScript React";

function App(props) {
  return JsxRuntime.jsxs("main", {
    children: [
      JsxRuntime.jsx("h1", {
        children: headingText
      }),
      JsxRuntime.jsx(Button.make, {}),
      JsxRuntime.jsx(Card.make, {})
    ],
    className: "rc_107y9ht_0"
  });
}

let make = App;

export {
  headingText,
  make,
}