// This stylesheet import is generated by @jvlk/rescript-css.
import "./App.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let page = "rc_107y9ht_0";

let title = "rc_107y9ht_1";

let button = "rc_107y9ht_2";

function App(props) {
  return JsxRuntime.jsxs("main", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Typed CSS in ReScript React",
        className: "rc_107y9ht_1"
      }),
      JsxRuntime.jsx("button", {
        children: "A styled button",
        className: "rc_107y9ht_2"
      })
    ],
    className: "rc_107y9ht_0"
  });
}

let make = App;

export {
  make,
}
/* page Not a pure module */
