// This stylesheet import is generated by @jvlk/rescript-css.
import "./Button.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.js";
import * as JsxRuntime from "react/jsx-runtime";

let label = "Shared variables";

function Button(props) {
  return JsxRuntime.jsx("button", {
    children: label,
    className: "rc_1qr011i_0"
  });
}

let make = Button;

export {
  label,
  make,
}