// This stylesheet import is generated by @jvlk/rescript-css.
import "./Button.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.js";
import * as CssValue from "@jvlk/rescript-css/src/CssValue.res.js";
import * as JsxRuntime from "react/jsx-runtime";

let radius = CssValue.BorderRadius.single({
  TAG: "Px",
  _0: 6
});

let tmp;

tmp = radius.TAG === "Ok" ? radius._0 : ({
    TAG: "Raw",
    _0: "6px"
  });

let label = "Shared variables";

function Button(props) {
  return JsxRuntime.jsx("button", {
    children: label,
    className: "rc_1qr011i_0"
  });
}

let make = Button;

export {
  label,
  make,
}