// This stylesheet import is generated by @jvlk/rescript-css.
import "./Card.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.js";
import * as JsxRuntime from "react/jsx-runtime";

let content = "This component overrides shared variables within its own scope.";

function Card(props) {
  return JsxRuntime.jsx("article", {
    children: content,
    className: "rc_19ciu9w_0"
  });
}

let make = Card;

export {
  content,
  make,
}