// This stylesheet import is generated by @jvlk/rescript-css.
import "./Card.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.js";
import * as CssValue from "@jvlk/rescript-css/src/CssValue.res.js";
import * as JsxRuntime from "react/jsx-runtime";

let radius = CssValue.BorderRadius.single({
  TAG: "Px",
  _0: 8
});

let tmp;

tmp = radius.TAG === "Ok" ? radius._0 : ({
    TAG: "Raw",
    _0: "8px"
  });

let radius$1 = CssValue.CornerRadius.circular({
  TAG: "Rem",
  _0: 1.5
});

let tmp$1;

tmp$1 = radius$1.TAG === "Ok" ? radius$1._0 : ({
    TAG: "Raw",
    _0: "1.5rem"
  });

let content = "This component overrides shared variables within its own scope.";

function Card(props) {
  return JsxRuntime.jsx("article", {
    children: content,
    className: "rc_19ciu9w_0"
  });
}

let make = Card;

export {
  content,
  make,
}