// This stylesheet import is generated by @jvlk/rescript-css.
import "./Vars.css";
// Generated by ReScript, PLEASE EDIT WITH CARE


let brand = "var(--rc_d0rg60)";

let onBrand = "var(--rc_jj8xyx)";

let surface = "var(--rc_yc142e)";

let text = "var(--rc_4pjwda)";

let spaceMd = "var(--rc_r1kdke)";


export {
  brand,
  onBrand,
  surface,
  text,
  spaceMd,
}
/* brand Not a pure module */
