// This stylesheet import is generated by @jvlk/rescript-css.
import "./App.css";
// Generated by ReScript, PLEASE EDIT WITH CARE


let className = "rc_p2c5wm_0";

let html = `<main class="` + className + `"><h1>ReScript 12</h1><p>CSS compiled with ReScript 12.3.1 and Vite 8.</p></main>`;

export {
  className,
  html,
}
/* className Not a pure module */
