// This stylesheet import is generated by @jvlk/rescript-css.
import "./App.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.mjs";
import * as View$Xote from "xote/src/View.res.mjs";
import * as Signal$Xote from "xote/src/Signal.res.mjs";
import * as XoteJSX$Xote from "xote/src/XoteJSX.res.mjs";
import * as Computed$Xote from "xote/src/Computed.res.mjs";

function App(props) {
  let count = Signal$Xote.make(0, undefined, undefined);
  let doubled = Computed$Xote.make(() => (Signal$Xote.get(count) << 1), undefined, undefined);
  let decrease = _event => Signal$Xote.update(count, value => value - 1 | 0);
  let reset = _event => Signal$Xote.set(count, 0);
  let increase = _event => Signal$Xote.update(count, value => value + 1 | 0);
  return XoteJSX$Xote.Elements.jsx("main", {
    class: "rc_e12d7f_0",
    children: XoteJSX$Xote.Elements.jsxs("section", {
      class: "rc_e12d7f_1",
      children: XoteJSX$Xote.array([
        XoteJSX$Xote.Elements.jsx("p", {
          class: "rc_e12d7f_2",
          children: View$Xote.child("Xote + rescript-css")
        }),
        XoteJSX$Xote.Elements.jsx("h1", {
          children: View$Xote.child("Signals, meet typed styles.")
        }),
        XoteJSX$Xote.Elements.jsx("p", {
          class: "rc_e12d7f_3",
          children: View$Xote.child("This counter pairs Xote's fine-grained updates with statically extracted CSS, shared variables, nested selectors, and responsive rules.")
        }),
        XoteJSX$Xote.Elements.jsxs("div", {
          class: "rc_e12d7f_4",
          attrs: [[
              "aria-live",
              "polite"
            ]],
          children: XoteJSX$Xote.array([
            XoteJSX$Xote.Elements.jsx("span", {
              class: "rc_e12d7f_5",
              children: View$Xote.child(() => Signal$Xote.get(count))
            }),
            XoteJSX$Xote.Elements.jsxs("span", {
              class: "rc_e12d7f_6",
              children: XoteJSX$Xote.array([
                View$Xote.child("Doubled"),
                XoteJSX$Xote.Elements.jsx("span", {
                  children: View$Xote.child(() => Signal$Xote.get(doubled))
                })
              ])
            })
          ])
        }),
        XoteJSX$Xote.Elements.jsxs("div", {
          class: "rc_e12d7f_7",
          children: XoteJSX$Xote.array([
            XoteJSX$Xote.Elements.jsx("button", {
              class: "rc_e12d7f_9",
              onClick: decrease,
              children: View$Xote.child("Decrease")
            }),
            XoteJSX$Xote.Elements.jsx("button", {
              class: "rc_e12d7f_9",
              onClick: reset,
              children: View$Xote.child("Reset")
            }),
            XoteJSX$Xote.Elements.jsx("button", {
              class: "rc_e12d7f_8",
              onClick: increase,
              children: View$Xote.child("Increase")
            })
          ])
        })
      ])
    })
  });
}

let make = App;

export {
  make,
}