// This stylesheet import is generated by @jvlk/rescript-css.
import "./App.css";
// Generated by ReScript, PLEASE EDIT WITH CARE

import "./Vars.res.mjs";
import * as CssValue from "@jvlk/rescript-css/src/CssValue.res.mjs";
import * as View$Xote from "xote/src/View.res.mjs";
import * as Signal$Xote from "xote/src/Signal.res.mjs";
import * as XoteJSX$Xote from "xote/src/XoteJSX.res.mjs";
import * as Computed$Xote from "xote/src/Computed.res.mjs";

let value = CssValue.TrackFraction.make(1.0);

let fractionalTrack;

fractionalTrack = value.TAG === "Ok" ? ({
    TAG: "Fraction",
    _0: value._0
  }) : ({
    TAG: "Raw",
    _0: "1fr"
  });

let match = CssValue.TrackLength.make("Zero");

let match$1 = CssValue.TrackFraction.make(1.0);

let match$2 = CssValue.RepeatCount.make(3);

let repeatedTracks;

repeatedTracks = match.TAG === "Ok" && match$1.TAG === "Ok" && match$2.TAG === "Ok" ? ({
    TAG: "Tracks",
    _0: [{
        TAG: "Repeat",
        _0: match$2._0,
        _1: [{
            TAG: "RepeatBreadth",
            _0: {
              TAG: "Minmax",
              _0: {
                TAG: "MinimumLength",
                _0: match._0
              },
              _1: {
                TAG: "MaximumFraction",
                _0: match$1._0
              }
            }
          }]
      }]
  }) : ({
    TAG: "Raw",
    _0: "repeat(3, minmax(0, 1fr))"
  });

let radius = CssValue.BorderRadius.single({
  TAG: "Px",
  _0: 8
});

let tmp;

tmp = radius.TAG === "Ok" ? radius._0 : ({
    TAG: "Raw",
    _0: "8px"
  });

let radius$1 = CssValue.BorderRadius.single({
  TAG: "Px",
  _0: 6
});

let tmp$1;

tmp$1 = radius$1.TAG === "Ok" ? radius$1._0 : ({
    TAG: "Raw",
    _0: "6px"
  });

let radius$2 = CssValue.BorderRadius.single({
  TAG: "Px",
  _0: 6
});

let tmp$2;

tmp$2 = radius$2.TAG === "Ok" ? radius$2._0 : ({
    TAG: "Raw",
    _0: "6px"
  });

let radius$3 = CssValue.BorderRadius.single({
  TAG: "Px",
  _0: 6
});

let tmp$3;

tmp$3 = radius$3.TAG === "Ok" ? radius$3._0 : ({
    TAG: "Raw",
    _0: "6px"
  });

function App(props) {
  let count = Signal$Xote.make(0, undefined, undefined);
  let doubled = Computed$Xote.make(() => (Signal$Xote.get(count) << 1), undefined, undefined);
  let decrease = _event => Signal$Xote.update(count, value => value - 1 | 0);
  let reset = _event => Signal$Xote.set(count, 0);
  let increase = _event => Signal$Xote.update(count, value => value + 1 | 0);
  return XoteJSX$Xote.Elements.jsx("main", {
    class: "rc_e12d7f_0",
    children: XoteJSX$Xote.Elements.jsxs("section", {
      class: "rc_e12d7f_1",
      children: XoteJSX$Xote.array([
        XoteJSX$Xote.Elements.jsx("p", {
          class: "rc_e12d7f_2",
          children: View$Xote.child("Xote + rescript-css")
        }),
        XoteJSX$Xote.Elements.jsx("h1", {
          children: View$Xote.child("Signals, meet typed styles.")
        }),
        XoteJSX$Xote.Elements.jsx("p", {
          class: "rc_e12d7f_3",
          children: View$Xote.child("This counter pairs Xote's fine-grained updates with statically extracted CSS, shared variables, nested selectors, and responsive rules.")
        }),
        XoteJSX$Xote.Elements.jsxs("div", {
          class: "rc_e12d7f_4",
          attrs: [[
              "aria-live",
              "polite"
            ]],
          children: XoteJSX$Xote.array([
            XoteJSX$Xote.Elements.jsx("span", {
              class: "rc_e12d7f_5",
              children: View$Xote.child(() => Signal$Xote.get(count))
            }),
            XoteJSX$Xote.Elements.jsxs("span", {
              class: "rc_e12d7f_6",
              children: XoteJSX$Xote.array([
                View$Xote.child("Doubled"),
                XoteJSX$Xote.Elements.jsx("span", {
                  children: View$Xote.child(() => Signal$Xote.get(doubled))
                })
              ])
            })
          ])
        }),
        XoteJSX$Xote.Elements.jsxs("div", {
          class: "rc_e12d7f_7",
          children: XoteJSX$Xote.array([
            XoteJSX$Xote.Elements.jsx("button", {
              class: "rc_e12d7f_9",
              onClick: decrease,
              children: View$Xote.child("Decrease")
            }),
            XoteJSX$Xote.Elements.jsx("button", {
              class: "rc_e12d7f_9",
              onClick: reset,
              children: View$Xote.child("Reset")
            }),
            XoteJSX$Xote.Elements.jsx("button", {
              class: "rc_e12d7f_8",
              onClick: increase,
              children: View$Xote.child("Increase")
            })
          ])
        })
      ])
    })
  });
}

let make = App;

export {
  make,
}
/* value Not a pure module */
