// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as View$Xote from "xote/src/View.res.mjs";
import * as XoteJSX$Xote from "xote/src/XoteJSX.res.mjs";

View$Xote.mountById(XoteJSX$Xote.jsx(App.make, {}), "app");

/*  Not a pure module */
