// This stylesheet import is generated by @jvlk/rescript-css.
import "./Vars.css";
// Generated by ReScript, PLEASE EDIT WITH CARE


let brand = "var(--rc_jbjej6)";

let onBrand = "var(--rc_ddsy7n)";

let canvas = "var(--rc_1xpsaip)";

let surface = "var(--rc_6ug87w)";

let text = "var(--rc_1by40t0)";

let muted = "var(--rc_j58jwk)";

let accent = "var(--rc_1u0z3vb)";

let border = "var(--rc_1wypgmd)";

let spaceMd = "var(--rc_4n84x0)";


export {
  brand,
  onBrand,
  canvas,
  surface,
  text,
  muted,
  accent,
  border,
  spaceMd,
}
/* brand Not a pure module */
