import * as Css from '../../../../src/Css.res.js';

const tagged = (TAG, ...payload) =>
  Object.fromEntries([['TAG', TAG], ...payload.map((value, index) => [`_${index}`, value])]);
const named = (value) => tagged('Named', value);
const px = (value) => tagged('Px', value);
const rem = (value) => tagged('Rem', value);
const percent = (value) => tagged('Percent', value);

const showcase = Css.style(undefined, {
  anchorName: '--trigger',
  anchorScope: '--trigger',
  positionAnchor: '--trigger',
  positionArea: 'top span-all',
  positionTry: 'most-width flip-block',
  positionTryFallbacks: '--below, flip-block',
  positionTryOrder: 'MostInlineSize',
  positionVisibility: tagged('Conditions', ['AnchorVisible', 'NoOverflow']),
  containIntrinsicSize: 'auto 300px',
  containIntrinsicWidth: tagged('AutoLength', rem(20)),
  containIntrinsicHeight: 'None',
  containIntrinsicBlockSize: tagged('AutoLength', rem(24)),
  containIntrinsicInlineSize: tagged('Length', rem(18)),
  colorScheme: 'light dark',
  forcedColorAdjust: 'PreserveParentColor',
  printColorAdjust: 'Exact',
  fontVariationSettings: '"wght" 650',
  fontPalette: '--brand-palette',
  fontSynthesis: tagged('Values', ['Weight', 'Style']),
  fontSizeAdjust: tagged('Metric', 'CapHeight', 0.7),
  textWrap: 'Balance',
  textWrapMode: 'NoWrap',
  textWrapStyle: 'Pretty',
  textEmphasis: 'filled sesame red',
  textOrientation: 'Upright',
  unicodeBidi: 'Isolate',
  hangingPunctuation: tagged('Values', ['First', 'AllowEnd']),
  lineClamp: tagged('Lines', 3),
  borderBlockStart: '1px solid red',
  borderBlockEnd: '2px dashed blue',
  borderInlineStart: '1px dotted green',
  borderInlineEnd: '3px double black',
  borderBlockColor: named('red'),
  borderBlockStartColor: named('red'),
  borderBlockEndColor: named('blue'),
  borderInlineColor: named('blue'),
  borderInlineStartColor: named('green'),
  borderInlineEndColor: named('black'),
  borderBlockStyle: 'Solid',
  borderBlockStartStyle: 'Solid',
  borderBlockEndStyle: 'Dashed',
  borderInlineStyle: 'Dashed',
  borderInlineStartStyle: 'Dotted',
  borderInlineEndStyle: 'Double',
  borderBlockWidth: tagged('One', tagged('Length', px(2))),
  borderBlockStartWidth: tagged('Length', px(1)),
  borderBlockEndWidth: tagged('Length', px(2)),
  borderInlineWidth: tagged('One', tagged('Length', rem(0.25))),
  borderInlineStartWidth: tagged('Length', px(1)),
  borderInlineEndWidth: tagged('Length', px(3)),
  borderStartStartRadius: tagged('Circular', rem(0.5)),
  borderStartEndRadius: tagged('Circular', rem(0.75)),
  borderEndStartRadius: tagged('Circular', px(6)),
  borderEndEndRadius: tagged('Circular', px(8)),
  translate: tagged('XY', rem(1), percent(20)),
  rotate: tagged('X', tagged('Deg', 45)),
  scale: tagged('XY', tagged('Number', 1.2), tagged('Percent', 80)),
  transformBox: 'FillBox',
  viewTransitionName: 'card-image',
  viewTransitionClass: 'card fast-slide',
  transitionBehavior: 'AllowDiscrete',
  offset: 'path("M 0 0 L 100 0") 50%',
  offsetPath: 'path("M 0 0 L 100 0")',
  offsetDistance: percent(50),
  offsetPosition: 'left top',
  offsetAnchor: 'center',
  offsetRotate: tagged('AutoAngle', tagged('Deg', 45)),
  fill: tagged('Color', tagged('Hex', '336699')),
  fillOpacity: tagged('Number', 0.6),
  fillRule: 'Evenodd',
  stroke: tagged('Color', 'CurrentColor'),
  strokeWidth: px(2),
  strokeOpacity: tagged('Percent', 75),
  strokeLinecap: 'Round',
  strokeLinejoin: 'Bevel',
  strokeDasharray: tagged('Values', [px(4), px(2)]),
  strokeDashoffset: px(1),
  strokeMiterlimit: 4,
  paintOrder: tagged('Values', ['Stroke', 'Fill', 'Markers']),
  vectorEffect: 'NonScalingStroke',
  stopColor: named('gold'),
  stopOpacity: tagged('Number', 0.8),
  scrollMarginTop: px(8),
  scrollMarginRight: px(9),
  scrollMarginBottom: px(10),
  scrollMarginLeft: px(11),
  scrollMarginBlock: tagged('One', rem(1)),
  scrollMarginBlockStart: px(12),
  scrollMarginBlockEnd: px(13),
  scrollMarginInline: tagged('One', rem(1.25)),
  scrollMarginInlineStart: px(14),
  scrollMarginInlineEnd: px(15),
  scrollPaddingTop: px(16),
  scrollPaddingRight: px(17),
  scrollPaddingBottom: px(18),
  scrollPaddingLeft: px(19),
  scrollPaddingBlock: tagged('One', rem(1.5)),
  scrollPaddingBlockStart: px(20),
  scrollPaddingBlockEnd: px(21),
  scrollPaddingInline: tagged('One', rem(1.75)),
  scrollPaddingInlineStart: px(22),
  scrollPaddingInlineEnd: px(23),
  overscrollBehaviorX: 'Contain',
  overscrollBehaviorY: 'None',
  overscrollBehaviorBlock: 'Contain',
  overscrollBehaviorInline: 'Auto',
  container: 'sidebar / inline-size',
  boxDecorationBreak: 'Clone',
  breakBefore: 'AvoidPage',
  breakAfter: 'Column',
  breakInside: 'AvoidColumn',
  orphans: 3,
  widows: 3,
  shapeOutside: 'circle(50%)',
  shapeMargin: rem(1),
  shapeImageThreshold: tagged('Number', 0.5),
  fieldSizing: 'Content',
  interpolateSize: 'AllowKeywords',
});

export { showcase };
